### ISSUE TITLE
Fix "Unexpected Application Error"

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#92]
Sometimes when opening the collector, this message appears:

![Image](https://github.com/hto-projects/autohack-idle/assets/106829895/3040c498-242c-4fa7-a3b5-e66e0a933abc)

Call stack:

```
TypeError: Cannot read properties of null (reading 'cut')
    at Frame2.setSize (http://localhost:3000/node_modules/.vite/deps/phaser.js?v=409b8fe3:120077:36)
    at Text2.updateText (http://localhost:3000/node_modules/.vite/deps/phaser.js?v=409b8fe3:46897:34)
    at Text2.setText (http://localhost:3000/node_modules/.vite/deps/phaser.js?v=409b8fe3:46333:28)
    at EventEmitter2.<anonymous> (http://localhost:3000/src/game/scenes/Collect.ts:57:24)
    at EventEmitter2.emit (http://localhost:3000/node_modules/.vite/deps/phaser.js?v=409b8fe3:107:45)
    at http://localhost:3000/src/game/PhaserGame.tsx:75:14
    at commitHookEffectListMount (http://localhost:3000/node_modules/.vite/deps/chunk-OCHDJWGW.js?v=409b8fe3:16904:34)
    at commitPassiveMountOnFiber (http://localhost:3000/node_modules/.vite/deps/chunk-OCHDJWGW.js?v=409b8fe3:18152:19)
    at commitPassiveMountEffects_complete (http://localhost:3000/node_modules/.vite/deps/chunk-OCHDJWGW.js?v=409b8fe3:18125:17)
    at commitPassiveMountEffects_begin (http://localhost:3000/node_modules/.vite/deps/chunk-OCHDJWGW.js?v=409b8fe3:18115:15)
```

Appears to be something related to Phaser

**Comment by jvgusch** [comment]
Reproduction steps (**Note**: this assumes you already have the "Check for Bits" and "Chance for Bits" upgrades purchased already. If you are starting from a fresh state, you will need to purchase those upgrades after Step 1 but before Step 2.):

1. Launch the game.
3. Open the "Collector" app.
4. Collect at least 1 bit.
5. Click the "Close" button.
6. Open the the "Upgrades" app.
7. Click the "Sell Data" button.
8. Click the "Close" button.
9. Open the "Collector" app.
10. \*\*\*Notice the error as described in the issue.\*\*\*
